version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  assignees:
  - kudos
  ignore:
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.8.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.11.2
    - 2.13.4
  - dependency-name: gatsby-remark-images
    versions:
    - 3.10.0
    - 3.8.1
  - dependency-name: gatsby
    versions:
    - 2.29.3
    - 2.31.1
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.13.1
    - 2.15.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.7.1
    - 3.9.0
  - dependency-name: react-icons
    versions:
    - 4.1.0
